# Generated by Django 4.2.18 on 2025-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, default='product_pictures/default.png', null=True, upload_to='product_pictures/'),
        ),
    ]
