# Generated by Django 4.2.18 on 2025-02-05 13:15

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_productavatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavatar',
            name='image',
            field=models.ImageField(upload_to=myapp.models.UniqueImagePath('product_avatars/')),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='product_pictures/default.png', upload_to=myapp.models.UniqueImagePath('product_pictures/')),
        ),
    ]
